<?xml version="1.0" encoding="utf-8"?><Database Name="SI_KASIR_PBO" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=SI_KASIR_PBO;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="SI_Kasir_Toko.Properties.Settings" SettingsPropertyName="SI_KASIR_PBOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Barang" Member="Barangs">
    <Type Name="Barang">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NamaBarang" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="HargaBarang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StokBarang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataMasuk" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Barang_Transaction" Member="Transactions" ThisKey="ID" OtherKey="IDBarang" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Alamat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MasukAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDBarang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JumlahTransaksi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalHarga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransaksiAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Barang_Transaction" Member="Barang" ThisKey="IDBarang" OtherKey="ID" Type="Barang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="CodeSupplier" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NamaSupplier" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Alamat" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NoRekening" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NPWP" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Kota" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Negara" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provinsi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KodePos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Barcode2" Member="Barcode2s">
    <Type Name="Barcode2">
      <Column Name="BarcodeID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stok" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Harga" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>